package com.vsnu.market.controllers;

import com.vsnu.market.entities.Variation;
import com.vsnu.market.repositories.VariationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/variations") // This means URL's start with /demo (after Application path)
public class VariationController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private VariationRepository variationRepository;

    @GetMapping(path="/{itemId}")
    public @ResponseBody Iterable<Variation> getAllVariationsOfAnItem(@PathVariable("itemId") Integer id) {
        // This returns a JSON or XML with the users
        return variationRepository.findByItemId(id);
    }
}